Задание 6. Добавлена функциональность регистрации пользователя
gpb-it-factory/shevela-middle-service pull request #4
Opened 2024-05-30 22:45 UTC by IvanAlShell

Задание 6. Добавлена функциональность регистрации пользователя по команде /register, проверка регистрации пользователя по команде /isregister, обновлен README, добавлена автоматизация gradle-build.yml

2024-06-06 06:09 UTC, DirtyRamirez requested changes

2024-06-06 06:09 UTC, DirtyRamirez commented on src/main/java/gpb/itfactory/shevelamiddleservice/controller/Controller.java
> +//            User user = usersList.getUserByUsername(telegramUserDto.getUsername()).get();
а подскажи, для чего закомментарено тут?

2024-06-06 06:09 UTC, DirtyRamirez commented on src/main/java/gpb/itfactory/shevelamiddleservice/controller/Controller.java
> +//            log.info(user.toString());
и тут

2024-06-06 06:09 UTC, DirtyRamirez commented on src/main/java/gpb/itfactory/shevelamiddleservice/controller/MockBackendController.java
> +        return ResponseEntity.status(606).body(ERROR_JSON); // !!!
что здесь?)

2024-06-06 06:09 UTC, DirtyRamirez commented on src/main/java/gpb/itfactory/shevelamiddleservice/entity/Error.java
> +    private String traceid;
`traceId`

2024-06-06 06:28 UTC, IvanAlShell commented on src/main/java/gpb/itfactory/shevelamiddleservice/controller/Controller.java
> +//            User user = usersList.getUserByUsername(telegramUserDto.getUsername()).get();
Это не нужно, что-то переделывал, забыл удалить

2024-06-06 06:29 UTC, IvanAlShell commented on src/main/java/gpb/itfactory/shevelamiddleservice/controller/Controller.java
> +//            log.info(user.toString());
Аналогично предыдущему, надо удалить

2024-06-06 06:40 UTC, IvanAlShell commented on src/main/java/gpb/itfactory/shevelamiddleservice/controller/MockBackendController.java
> +        return ResponseEntity.status(606).body(ERROR_JSON); // !!!
Заглушка) чтобы протестировать middle service. А странный статус код чтобы не ловить exception, которое вылетает при 500. В спецификации не указан код ответа, поэтому решил что на данном этапе это не важно и главное включить json в response body. Полагаю, этот класс надо удалить и использовать WireMock?

2024-06-09 20:42 UTC, IvanAlShell commented
Спасибо за обратную связь! Исправлены замечания, удалены ненужные комментарии и классы, в связи с крайними вводными от Вадима исправлена логика - для регистрации используется юзернейм и айдишник, также добавлены интеграционные тесты

2024-06-13 06:01 UTC, DirtyRamirez approved these changes
отлично!)

2024-06-13 20:17 UTC, merged